host: account.jetbrains.com
encodedPath: /api/v1/
xCustomerCode:
xApiKey:
mainUser:
  email:
  firstName:
  lastName:
secondUser:
  email:
  firstName: Test
  lastName: Test
customerLicensesAssignPath: customer/licenses/assign
customerLicensesPath: customer/licenses
customerLicensesByIdPath: customer/licenses/{licenseId}
customerTeamLicensesByTeamIdPath: customer/teams/{teamId}/licenses
customerChangeLicensesTeam: customer/changeLicensesTeam
