host: account.jetbrains.com
encodedPath: /api/v1/
x-customer-code:
x-api-key:
firstName:
lastName:
email:
fakeFirstName: FakeFirstName
fakeLastName: FakeLastName
fakeEmail: fakee_mail@example.com
customerLicensesAssignPath: customer/licenses/assign
customerLicensesPath: customer/licenses
customerLicensesByIdPath: customer/licenses/{licenseId}
customerTeamLicensesByTeamIdPath: customer/teams/{teamId}/licenses
